//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateFileInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UpdateFileInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AutoUpdateService.AutoUpdateSoap")]
    public interface AutoUpdateSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetAllUpdateFileInfoResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUpdateFileInfo", ReplyAction="*")]
        KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.GetAllUpdateFileInfoResponse GetAllUpdateFileInfo(KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.GetAllUpdateFileInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUpdateFileInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUpdateFileInfo", Namespace="http://tempuri.org/", Order=0)]
        public KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.GetAllUpdateFileInfoRequestBody Body;
        
        public GetAllUpdateFileInfoRequest() {
        }
        
        public GetAllUpdateFileInfoRequest(KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.GetAllUpdateFileInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUpdateFileInfoRequestBody {
        
        public GetAllUpdateFileInfoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUpdateFileInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUpdateFileInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.GetAllUpdateFileInfoResponseBody Body;
        
        public GetAllUpdateFileInfoResponse() {
        }
        
        public GetAllUpdateFileInfoResponse(KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.GetAllUpdateFileInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllUpdateFileInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.UpdateFileInfo[] GetAllUpdateFileInfoResult;
        
        public GetAllUpdateFileInfoResponseBody() {
        }
        
        public GetAllUpdateFileInfoResponseBody(KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.UpdateFileInfo[] GetAllUpdateFileInfoResult) {
            this.GetAllUpdateFileInfoResult = GetAllUpdateFileInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AutoUpdateSoapChannel : KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.AutoUpdateSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutoUpdateSoapClient : System.ServiceModel.ClientBase<KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.AutoUpdateSoap>, KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.AutoUpdateSoap {
        
        public AutoUpdateSoapClient() {
        }
        
        public AutoUpdateSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutoUpdateSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoUpdateSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoUpdateSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.GetAllUpdateFileInfoResponse KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.AutoUpdateSoap.GetAllUpdateFileInfo(KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.GetAllUpdateFileInfoRequest request) {
            return base.Channel.GetAllUpdateFileInfo(request);
        }
        
        public KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.UpdateFileInfo[] GetAllUpdateFileInfo() {
            KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.GetAllUpdateFileInfoRequest inValue = new KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.GetAllUpdateFileInfoRequest();
            inValue.Body = new KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.GetAllUpdateFileInfoRequestBody();
            KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.GetAllUpdateFileInfoResponse retVal = ((KeerSolutions.MobileCommerce.AutoUpdate.AutoUpdateService.AutoUpdateSoap)(this)).GetAllUpdateFileInfo(inValue);
            return retVal.Body.GetAllUpdateFileInfoResult;
        }
    }
}
